git-sync.sh autocommit

diff --git a/zim b/zim
--- a/zim
+++ b/zim
@@ -29,6 +29,16 @@ echo -e "$(date +%s)\tzim $*" >> $LOG
 # KDE-only? https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/580
 export LC_ALL=C
 
+function debug()
+{
+	echo 1>&2 "debug: $*"
+}
+
+function warning()
+{
+	echo 1>&2 "warning: $*"
+}
+
 # NB: duplicated in ~/etc/cron.*/zim-commit.sh
 function zim_is_running()
 {
@@ -42,6 +52,7 @@ function zim_is_running()
 
 function start_sidekick()
 {
+	debug start_sidekick
 	local LOG=/tmp/zim-sidekick.log
 	SIDEKICK="$(which zim-sidekick-loop)" 2> /dev/null
 
@@ -50,15 +61,21 @@ function start_sidekick()
 		# Should it have it's own log?
 		( cd / ; "$SIDEKICK" >> $LOG 2>&1 ) &
 		SIDEKICK_PID="$!"
+	else
+		debug "sidekick not found"
 	fi
 }
 
 function stop_sidekick()
 {
+	debug stop_sidekick
 	#local PID="${SIDEKICK_PID:-}"
 	#test -z "$PID" || kill "$PID"
-	killall zim-sidekick-loop
+	#killall zim-sidekick-loop
+	pkill -f zim-sidekick-loop
 }
+
+#set -vx
 
 SOCKET=$(find /tmp/zim-$USER -type s)
 
@@ -66,6 +83,7 @@ SOCKET=$(find /tmp/zim-$USER -type s)
 # so merge any stray branches and inject a "--debug" argument.
 if [ $# -eq 0 ]
 then
+	debug "no arguments given -> GUI_LAUNCH"
 
 	# If we are launching the gui, make sure there are no other guis running.
 	# NB: This is done *before* prelaunch b/c prelaunch will utterly destroy the running zim's /tmp/zim-$USER directory.
@@ -81,23 +99,57 @@ then
 		#gxmessage -print -title Error 'Zim socket is present, but not running?'
 		#exit 1
 		rm -fv "$SOCKET"
+		SOCKET=""
 	fi
 
 	# NB: The pre-launch merge usually brings in a 'flip-flop-change'... so it must be done before claiming that mutex.
 	if [ -x "$PRELAUNCH" ]
 	then
+		debug "activating prelaunch"
 		$PRELAUNCH
+		debug "prelaunch complete"
 	else
-		echo 1>&2 "$PRELAUNCH: dne"
+		debug "$PRELAUNCH: dne"
 	fi
 
+	GUI_LAUNCH=true
 	set -- --debug
+else
+	GUI_LAUNCH=""
+
+	TIMES=0
+	while [ -z "$SOCKET" ]
+	do
+		debug "non-gui zim call without a socket waiting for zim to activate"
+
+		sleep 60
+		let TIMES=TIMES+1
+
+		if [ "$TIMES" -gt "10" ]
+		then
+			warning "waited too long for zim to come alive"
+			break
+		fi
+
+		if zim_is_running
+		then
+			SOCKET=$(find /tmp/zim-$USER -type s)
+		else
+			warning "non-gui zim call without main zim process present"
+			break
+		fi
+	done
 fi
 
-#echo "$$" > /tmp/zim.pid.$$
+# At this point, one of two things *should* usually be true. Either:
+# (1) we are called as 'zim' (no args) and there is no socket, or
+# (2) we are called as 'zim ...' (with args) and there is a socket to the main zim instance.
 
-if [ -n "$SOCKET" ]
+#if [ -n "$SOCKET" ]
+if [ -z "$GUI_LAUNCH" ]
 then
+	debug "non-gui launch"
+
 	# Make sure we don't lose the socket
 	if [ -d "$LOCAL" ]
 	then
@@ -106,7 +158,7 @@ then
 		export PYTHONPATH="$LOCAL"
 		$LOCAL/zim.py "$@"
 	else
-		echo 1>&2 "WARNING: using $STOCK"
+		warning "using stock zim: $STOCK"
 		"$STOCK" "$@"
 	fi
 
@@ -118,7 +170,8 @@ then
 			echo 1>&2 "NOTICE: still don't have a socket... okay..."
 		else
 			echo 1>&2 "WARNING: socket vanished: $SOCKET"
-			pom-notable "[[:Zim:Socket:Vanish]]"
+			pom-notable "[[:Zim:Socket:Vanish]] (noticed after non-gui/background zim call)"
+
 			# YES... this is *VERY* aggressive, but I often find that in this state a normal TERM does not suffice,
 			# AND... 'zim' is called very frequently, so I don't want to TERM, sleep, KILL...
 			# FURTHER... it is almost SURELY *THIS*CALL* (that we just made above) that eradicated the socket, so this
@@ -129,16 +182,19 @@ then
 		fi
 	fi
 else
+	debug "gui launch requested"
+	sleep 1
+
 	# We should not have zim running w/o a socket... but can we tell the difference between the server & client processes?
 	# If we leave it running, then we will have a bunch of ugly race conditions.
 	if zim_is_running
 	then
 		echo 1>&2 "WARNING: socket vanished: $SOCKET"
-		pom-notable "[[:Zim:Socket:Vanish]]"
-		pgrep -f 'zim.py --debug' | xargs kill -9 || echo "could not kill -9 zim server?"
+		pom-notable "[[:Zim:Socket:Vanish]] (requested zim gui launch noticed pre-existing zim gui thread running without a control socket)"
+		pgrep -f 'zim.py --debug' | xargs kill -9 || echo "could not kill -9 zim development server?"
+		pgrep -f 'zim --debug' | xargs kill -9 || echo "could not kill -9 zim stock server?"
 	fi
 
-	# Don't keep an extra shell around
 	if [ -d "$LOCAL" ]
 	then
 		#echo 1>&2 "using $LOCAL"
@@ -166,6 +222,7 @@ else
 		#########################################################################################################################
 	else
 		echo 1>&2 "WARNING: using $STOCK"
+		sleep 5
 		# Pardon the no-op slide... :-/
 		#########################################################################################################################
 		#########################################################################################################################
@@ -191,7 +248,7 @@ else
 	SOCKET2=$(find /tmp/zim-$USER -type s)
 	if [ -n "$SOCKET2" ]
 	then
-		pom-notable "~/bin/zim: launching non-gui zim left a socket active?"
+		pom-notable "zim: gui launch returned but socket lingers?"
 	fi
 fi
 
